name: Build Plugin
on: [ push ]
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.2
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - run: "./gradlew build"